### ISSUE TITLE
Unable to set shortcuts key-bind in Debian

### ISSUE THREAD

**Issue by WECLEYArtz** [wojtryb/Shortcut-Composer#87]
**General info**
- Plugin version: 
- `[ v1.5.3], krita flatpak 5.2.0`
- Operating System: 
```
Distributor ID: Debian
Description:    Debian GNU/Linux 12 (bookworm)
Release:        12
Codename:       bookworm

KDE plasmashell 5.27.5
```

**Bug description**
unable to set keybindings, video explains it all

[piessue (1).webm](https://github.com/wojtryb/Shortcut-Composer/assets/80406334/1709a6f9-b6d5-4600-b1d9-1277a4ad2e2e)

**Comment by wojtryb** [comment]
Hi,

I see you're using krita installed from flatpak which is not officially supported. Could you check out appimage from [official website](https://krita.org/en/download/)? - which is the only supported way to have krita on linux.

It's common for krita in distro repo to have wrong dependencies - if appimage works, and debian/flatpak do not - the issue can probably only be solved by debian/flatpak owners.

Also you need krita 5.2.2 to run current version of the plugin.

**Comment by WECLEYArtz** [comment]
Yeah i made a mistake it was 5.2.2.

Just tried .appimage and the issue remains the same as flatpak

**Comment by WECLEYArtz** [comment]
so appimage has been tried, the issue remains the same as flatpak, latest Krita version 5.2.2.

**Comment by WECLEYArtz** [comment]
Ok my bad, the plugin works in Flatpak, searching the shortcuts won't allow you change the bindings from the result, you'll have to look for them manually without using search by text.
